# Generated by Django 6.0.4 on 2026-05-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='token_verificacion',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
    ]
