# Generated by Django 6.0.4 on 2026-05-02 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(blank=True, help_text='Emoji o clase de icono', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('url_base', models.URLField()),
                ('auth_tipo', models.CharField(choices=[('none', 'Sin autenticación'), ('apikey', 'API Key'), ('oauth', 'OAuth')], default='none', max_length=20)),
                ('documentacion_url', models.URLField(blank=True)),
                ('ejemplo_endpoint', models.CharField(blank=True, help_text='Ruta de ejemplo: /pokemon/ditto', max_length=300)),
                ('parametros_ejemplo', models.JSONField(blank=True, default=dict, help_text='{"q": "Madrid", "units": "metric"}')),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apis', to='apis.categoria')),
            ],
            options={
                'verbose_name_plural': 'APIs',
                'ordering': ['nombre'],
            },
        ),
    ]
