# Generated by Django 6.0.4 on 2026-05-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='render_tipo',
            field=models.CharField(choices=[('json', 'JSON'), ('pokemon', 'Pokémon'), ('iss', 'Mapa ISS'), ('crypto', 'Gráfica Crypto')], default='json', max_length=20),
        ),
        migrations.AlterField(
            model_name='api',
            name='ejemplo_endpoint',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='api',
            name='parametros_ejemplo',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
