# Generated by Django 6.0.4 on 2026-05-05 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_api_render_tipo_alter_api_ejemplo_endpoint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='puntuacion_promedio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='api',
            name='total_puntuaciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PuntuacionApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='apis.api')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'api')},
            },
        ),
    ]
