# Generated by Django 6.0.4 on 2026-05-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_api_puntuacion_promedio_api_total_puntuaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='render_tipo',
            field=models.CharField(choices=[('json', 'JSON'), ('pokemon', 'Pokémon'), ('iss', 'Mapa ISS'), ('crypto', 'Gráfica Crypto'), ('apod', 'NASA APOD'), ('meal', 'TheMealDB'), ('country', 'RestCountries')], default='json', max_length=20),
        ),
    ]
