# Generated by Django 6.0.4 on 2026-05-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_api_render_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='total_visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
