# Generated by Django 6.0.4 on 2026-05-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_api_total_visitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='implementada',
            field=models.BooleanField(default=False),
        ),
    ]
