# Generated by Django 6.0.4 on 2026-05-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_api_render_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='render_tipo',
            field=models.CharField(choices=[('json', 'JSON'), ('pokemon', 'Pokémon'), ('iss', 'Mapa ISS'), ('crypto', 'Gráfica Crypto'), ('apod', 'NASA APOD'), ('meal', 'TheMealDB'), ('country', 'RestCountries'), ('weather', 'Clima Open-Meteo'), ('joke', 'JokeAPI')], default='json', max_length=20),
        ),
    ]
